version: '3.5'

services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: terraform_backend # Database default para o backend
    ports:
      - "5432:5432"
    networks:
      - terraform-network

networks:
  terraform-network:
    driver: bridge